### PR TITLE
Add CocoaPods support

### PR DESCRIPTION
**Pull request by tomassliz**
Hello,

I would like to offer the **CocoaPods** implementation for your library. I created Xcode dynamic framework project and include your source files into it. Then I created podspec file, I updated README file and I added .gitignore file.

If you will accept this PR, there are two things you have to do:
1. Create tag `1.0.0`.
2. Publish pod to the official CocoaPods repository (I can help you with that if you don't know how to do it).

Thank you

### CODE REVIEW

**Comment by tomassliz** [comment]
Hello, is any progress here?

**Comment by Sharrp** [comment]
Hello.

Sorry for not responding.
Will do all required work today.

**Comment by Sharrp** [comment]
Looks like it works now. Tomas please check that everything looks like you expected.
And thank you for your contribution!

**Comment by Sharrp** [comment]
Done

**Comment by tomassliz** [comment]
Thank you! I checked everything up and I pushed this pod to the CocoaPods trunk. Now everything works as a charm 🎉

**Comment by Sharrp** [comment]
Nice work 👍
Thank you

**Pull request merged**
